### ISSUE TITLE
xcode8 is crash

### ISSUE THREAD

**Issue by proflli** [ksuther/KSImageNamed-Xcode#86] opened 2016-09-27 02:22 UTC
After installing the software, open the Xcode8, enter any letter then Xcode8 crash

Process:               Xcode [875]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               8.0 (11246)
Build Info:            IDEFrameworks-11246000000000000~3
App Item ID:           497799835
App External ID:       818744938
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [875]
User ID:               501

Date/Time:             2016-09-27 10:21:09.545 +0800
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        F636BCDC-EEBA-7135-7E28-F874D73FEDD8

Time Awake Since Boot: 460 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
ProductBuildVersion: 8A218a
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): Error getting value for key 'strategyClass' of extension 'KSImageNamed.CompletionStrategy.ImageNamed' in plug-in 'com.ksuther.KSImageNamed'
UserInfo: {
    NSUnderlyingError = "Error Domain=DVTPlugInErrorDomain Code=2 \"Loading a plug-in failed.\" UserInfo={DVTPlugInIdentifierErrorKey=com.ksuther.KSImageNamed, DVTPlugInExecutablePathErrorKey=/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed, 0): no suitable image found.  Did find:\n\t/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed: code signing blocked mmap() of '/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed', NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin, NSLocalizedFailureReason=The plug-in \U201ccom.ksuther.KSImageNamed\U201d at path \U201c/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin\U201d could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7fab3efe6450 {Error Domain=NSCocoaErrorDomain Code=3587 \"dlopen_preflight(/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed): no suitable image found.  Did find:\n\t/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed: code signing blocked mmap() of '/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed'\" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed, NSDebugDescription=dlopen_preflight(/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed): no suitable image found.  Did find:\n\t/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed: code signing blocked mmap() of '/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed', NSBundlePath=/Users/proflli/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin, NSLocalizedDescription=The bundle \U201cKSImageNamed\U201d couldn\U2019t be loaded because it is damaged or missing necessary resources.}}}";
}

**Comment by ksuther** [comment] 2016-09-27 02:55
Based on that error is seems like Xcode is having trouble loading the bundle.

**Comment by yuanlingqi** [comment] 2016-09-27 07:06
I also encountered this problem，any help?

**Comment by proflli** [comment] 2016-09-28 00:24
How to solve this bug？

**Comment by ksuther** [comment] 2016-09-28 00:26
I'm going to need some help reproducing this, otherwise it's not going to get fixed.

**Comment by jinke5245** [comment] 2016-09-28 03:56
I also got this bug at Xcode 8, and got crash when i was coding.
I remove this plugin at `~/Library/Developer/Xcode/Plug-ins/`.

**Comment by HugSea** [comment] 2016-09-28 04:26
I also crash,  but I can't find KSImageNamed plugin at ~/Library/Developer/Xcode/Plug-ins/

**Comment by jinke5245** [comment] 2016-09-29 01:47
@HugSea 
`~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`.
Try to find at this file path.

**Comment by proflli** [comment] 2016-09-29 02:02
I have removed this plugins, and wait for the update.

**Comment by lzzhoujielun** [comment] 2016-10-19 16:14
I crash too, I will reinstall the xcode  . In xcode8 where set photo tip？

**Comment by ivanyang1984** [comment] 2016-10-21 04:44
@jinke5245 your solution works!

**Comment by wybflb** [comment] 2016-10-27 08:53
I meet the same error,Can anyone help?

**Comment by proflli** [comment] 2016-10-27 08:56
remove it! @wybflb

**Comment by wybflb** [comment] 2016-10-27 09:06
@proflli 使用OC语言，在Xcode8上，有其他库可以替换么？

**Comment by lyb5834** [comment] 2016-10-31 02:09
I carsh too,I have removed this plugins, and wait for the update.Can anyone tell me when it updated?

**Comment by galambalazs** [comment] 2016-11-04 11:34
crashes for me too in Xcode 8.1

(out of 20 plugins this was the only one so far)

**Comment by AMEstudio** [comment] 2016-11-14 07:26
look,i have the way to use on xcode8.0+ (8.1 also worked)
1.clean your xcode(make sure your xcode is pure)
2.delete all plug-ins

p.s.
location of plug-ins is:
> ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins
> /Users/YOUR USER NAME OF SYSTEM/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins

3.use this way to resign your xcode
https://github.com/XVimProject/XVim/blob/master/INSTALL_Xcode8.md
(thanks to the author of XVim)

4.download the KSImageNamed zip file

5.if your xcode is xcode8.0 just run the project of KSImageNamed
if your xcode is xcode8.1
you must add xcode8.1's uuid to the KSImage's project
-------
the way to add uuid is:
find a plist file in KSImageNamed's project which is named 'KSImageNamed-Info.plist'
add xcode8.1's uuid to array 'DVTPlugInCompatibilityUUIDs'
BTW the xcode8.1's uuid is 
`DA4FDFD8-C509-4D8B-8B55-84A7B66AE701`
and then run the project
--------

6.close your xcode and restart.
it will show a alert 
just choose loadbundle on the left.

7.enjoy :)

**Comment by heyehao2008** [comment] 2016-11-14 10:08
@AMEstudio  thanks ,it works for me !  for xcode 8.1
the important step is add your xcode's uuid to the KSImage's project, then build it.
after build , this path  `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins ` may not show KSImageNamed plugin ,but do not worry, just restart xcode ,it will show loadbundle alert.
BTW, don't have to delete all plug-ins

**Comment by strawnut** [comment] 2016-12-20 09:28
If you has encountered xcode crash after update xcode(although that's minor version:8.2 -> 8.2.1), the mention of @AMEstudio will be helped.

**Comment by casperSNSN** [comment] 2017-01-04 10:08
I met the same problem，@jinke5245 your solution works!

**Comment by xiky** [comment] 2017-02-22 10:07
it's a nice plug-ins for iOS develoer, so hope you can continus to develop

**Comment by ksuther** [comment] 2017-03-29 02:21
Closing because this crash occurs when Xcode hasn't been unsigned or re-signed.

**Closed by ksuther** 2017-03-29 02:21 UTC
